CREATE TABLE IF NOT EXISTS addresses (
  address_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country VARCHAR(50),
  city VARCHAR(50),
  street VARCHAR(50),
  house VARCHAR (20),
  flat VARCHAR (20)
);

CREATE TABLE IF NOT EXISTS deliveries (
  delivery_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  from_address BIGINT REFERENCES addresses(address_id),
  to_address BIGINT REFERENCES addresses(address_id) ,
  order_id UUID NOT NULL,
  delivery_state VARCHAR(50),
  delivery_weight NUMERIC(10, 2) NOT NULL,
  delivery_volume NUMERIC(10, 2) NOT NULL,
  fragile BOOLEAN
);