aggregator:
  topic:
    telemetry-snapshots: telemetry.snapshots.v1

topic:
  telemetry-sensors: telemetry.sensors.v1

spring:
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer

    consumer:
      client-id: AggregatorConsumer
      group-id: group_id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: ru.yandex.practicum.kafka.deserializer.SensorEventDeserializer
      enable-auto-commit: false
