spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      hub-client-id: HubConsumer
      hub-group-id: analyzer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      hub-deserializer: ru.yandex.practicum.kafka.deserializer.HubEventDeserializer
      enable-auto-commit: false
      snapshot-client-id: SnapshotConsumer
      snapshot-group-id: analyzer
      snapshot-deserializer: ru.yandex.practicum.kafka.deserializer.SnapshotDeserializer

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show_sql: true

  sql:
    init:
      mode: always

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/smart-home
    username: postgres
    password: password

grpc:
  client:
    hub-router:
      address: static://localhost:59090
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

topic:
  snapshots-topic: telemetry.snapshots.v1
  hub-event-topic: telemetry.hubs.v1